apiVersion: v1
kind: BuildConfig
metadata:
  labels:
    app: bluegreen
  name: bluegreen
  pipeline.alpha.openshift.io/uses: '[{"name": "bluegreen", "kind": "DeploymentConfig"}]'
spec:
  output:
    to:
      kind: ImageStreamTag
      name: bluegreen:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/bit4man/bluegreen
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
status:
