apiVersion: v1
kind: BuildConfig
metadata:
  name: php-bluegreen-app-pipeline
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: 'https://github.com/tariq-islam/ruby-mysql-app'
      ref: ocp33-pipeline
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
  output:
    to:
      kind: ImageStreamTag
      name: 'php-bluegreen-app:latest'
status:

